// Best Current Practices (BCP) for language tags
const LANGUAGES = [
  { code: "ar-SA", text: "Arabic	Saudi Arabia	Arabic (Saudi Arabia)" },
  { code: "bn-BD", text: "Bangla	Bangladesh	Bangla (Bangladesh)" },
  { code: "bn-IN", text: "Bangla	India	Bangla (India)" },
  { code: "cs-CZ", text: "Czech	Czech Republic	Czech (Czech Republic)" },
  { code: "da-DK", text: "Danish	Denmark	Danish (Denmark)" },
  { code: "de-AT", text: "German	Austria	Austrian German" },
  { code: "de-CH", text: "German	Switzerland	Swiss German" },
  {
    code: "de-DE",
    text: "German	Germany	Standard German (as spoken in Germany)",
  },
  { code: "el-GR", text: "Greek	Greece	Modern Greek" },
  { code: "en-AU", text: "English	Australia	Australian English" },
  { code: "en-CA", text: "English	Canada	Canadian English" },
  { code: "en-GB", text: "English	United Kingdom	British English" },
  { code: "en-IE", text: "English	Ireland	Irish English" },
  { code: "en-IN", text: "English	India	Indian English" },
  { code: "en-NZ", text: "English	New Zealand	New Zealand English" },
  { code: "en-US", text: "English	United States	US English" },
  { code: "en-ZA", text: "English	South Africa	English (South Africa)" },
  { code: "es-AR", text: "Spanish	Argentina	Argentine Spanish" },
  { code: "es-CL", text: "Spanish	Chile	Chilean Spanish" },
  { code: "es-CO", text: "Spanish	Columbia	Colombian Spanish" },
  {
    code: "es-ES",
    text: "Spanish	Spain	Castilian Spanish (as spoken in Central-Northern Spain)",
  },
  { code: "es-MX", text: "Spanish	Mexico	Mexican Spanish" },
  { code: "es-US", text: "Spanish	United States	American Spanish" },
  { code: "fi-FI", text: "Finnish	Finland	Finnish (Finland)" },
  { code: "fr-BE", text: "French	Belgium	Belgian French" },
  { code: "fr-CA", text: "French	Canada	Canadian French" },
  { code: "fr-CH", text: "French	Switzerland	Swiss French" },
  { code: "fr-FR", text: "French	France	Standard French (especially in France)" },
  { code: "he-IL", text: "Hebrew	Israel	Hebrew (Israel)" },
  { code: "hi-IN", text: "Hindi	India	Hindi (India)" },
  { code: "hu-HU", text: "Hungarian	Hungary	Hungarian (Hungary)" },
  { code: "id-ID", text: "Indonesian	Indonesia	Indonesian (Indonesia)" },
  { code: "it-CH", text: "Italian	Switzerland	'Swiss' Italian" },
  { code: "it-IT", text: "Italian	Italy	Standard Italian (as spoken in Italy)" },
  { code: "ja-JP", text: "Japanese	Japan	Japanese (Japan)" },
  { code: "ko-KR", text: "Korean	Republic of Korea	Korean (Republic of Korea)" },
  { code: "nl-BE", text: "Dutch	Belgium	Belgian Dutch" },
  {
    code: "nl-NL",
    text: "Dutch	The Netherlands	Standard Dutch (as spoken in The Netherlands)",
  },
  { code: "no-NO", text: "Norwegian	Norway	Norwegian (Norway)" },
  { code: "pl-PL", text: "Polish	Poland	Polish (Poland)" },
  { code: "pt-BR", text: "Portugese	Brazil	Brazilian Portuguese" },
  {
    code: "pt-PT",
    text: "Portugese	Portugal	European Portuguese (as written and spoken in Portugal)",
  },
  { code: "ro-RO", text: "Romanian	Romania	Romanian (Romania)" },
  {
    code: "ru-RU",
    text: "Russian	Russian Federation	Russian (Russian Federation)",
  },
  { code: "sk-SK", text: "Slovak	Slovakia	Slovak (Slovakia)" },
  { code: "sv-SE", text: "Swedish	Sweden	Swedish (Sweden)" },
  { code: "ta-IN", text: "Tamil	India	Indian Tamil" },
  { code: "ta-LK", text: "Tamil	Sri Lanka	Sri Lankan Tamil" },
  { code: "th-TH", text: "Thai	Thailand	Thai (Thailand)" },
  { code: "tr-TR", text: "Turkish	Turkey	Turkish (Turkey)" },
  { code: "zh-CN", text: "Chinese	China	Mainland China, simplified characters" },
  { code: "zh-HK", text: "Chinese	Hond Kong	Hong Kong, traditional characters" },
  { code: "zh-TW", text: "Chinese	Taiwan	Taiwan, traditional characters" },
];

export default LANGUAGES;
